#!/usr/bin/env python3
# coding: utf-8
from pathlib import Path
import matplotlib.pyplot as plt
from collections import OrderedDict

library = [
    l.split("\t")
    for l in Path("~/music/library.tsv").expanduser().read_text().splitlines()[1:-1]
]

counts = {artist: len([a for a, _ in library if a == artist]) for artist, _ in library}
filtered = {k:v for k, v in counts.items() if v >= 10}
ordered = OrderedDict(sorted(filtered.items(), key=lambda i: i[1]))


plt.barh(list(ordered.keys()), list(ordered.values()))
plt.show()
